### ISSUE TITLE
Races in NearCacheTest

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast#11091]
**testGetAsyncIssue1863()**
```
java.lang.AssertionError: Near Cache hits should be 1000 but were 996 expected:<1000> but was:<996>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at com.hazelcast.map.impl.nearcache.NearCacheTest.testGetAsyncIssue1863(NearCacheTest.java:565)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast%20Maintenance/job/Hazelcast-3.maintenance-IbmJDK1.7/com.hazelcast$hazelcast/549/testReport/junit/com.hazelcast.map.impl.nearcache/NearCacheTest/testGetAsyncIssue1863_batchInvalidationEnabled_true_/

**Comment by Donnerbart** [comment]
Should be the same root cause as https://github.com/hazelcast/hazelcast/issues/10988

**Comment by ahmetmircik** [comment]
should be fixed via 158aa74e02ecaf3758f928ed2cb78bdc8b265e60

**Comment by Donnerbart** [comment]
Seems to still fail.
```java
java.lang.AssertionError: Near Cache hits should be 1000 but were 998. All stats are here = [NearCacheStatsImpl{ownedEntryCount=999, ownedEntryMemoryCost=75924, creationTime=1502825964342, hits=998, misses=1002, ratio=99.6%, evictions=0, expirations=0, lastPersistenceTime=0, persistenceCount=0, lastPersistenceDuration=0, lastPersistenceWrittenBytes=0, lastPersistenceKeyCount=0, lastPersistenceFailure=''}] expected:<1000> but was:<998>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at com.hazelcast.map.impl.nearcache.NearCacheTest.testGetAsyncIssue1863(NearCacheTest.java:577)
```
https://hazelcast-l337.ci.cloudbees.com/job/new-lab-fast-pr/10200/testReport/junit/com.hazelcast.map.impl.nearcache/NearCacheTest/testGetAsyncIssue1863_batchInvalidationEnabled_true_/

I have to check the test, but maybe it's already covered by the unified ones (we have at least GET_ASYNC in there). Then we can simply remove it. Otherwise we need to port it, since this looks like our invalidation race.

**Comment by Donnerbart** [comment]
Also failed on a local run:
```
java.lang.AssertionError: Near Cache hits should be 1000 but were 996. All stats are here = [NearCacheStatsImpl{ownedEntryCount=1000, ownedEntryMemoryCost=76000, creationTime=1502919440206, hits=996, misses=1004, ratio=99.2%, evictions=0, expirations=0, lastPersistenceTime=0, persistenceCount=0, lastPersistenceDuration=0, lastPersistenceWrittenBytes=0, lastPersistenceKeyCount=0, lastPersistenceFailure=''}] 
Expected :1000
Actual   :996
```
Solution is still to migrate this test to the unified tests with the safe population.
