### ISSUE TITLE
Lock.tryLock with lease time

### ISSUE THREAD

**Issue by gurbuzali** [hazelcast/hazelcast#1564]
Hazelcast has lock with lease time feature but does not support tryLock with lease time

**Comment by tcollinsworth** [comment]
Is tryLock with lease time now supported? I see this was closed, but don't see that it was resolved.

**Comment by gurbuzali** [comment]
this is an open issue, we've not yet solved it.
the closed one was only a duplicate. Please see https://github.com/hazelcast/hazelcast/issues/3692

**Comment by logemann** [comment]
is this so hard to implement? I mean... one year and counting.... looks like copy/paste to me from the normal "lock" feature.

**Comment by noctarius** [comment]
Hey @logemann, yeah I guess you're kinda right.
Would you like to give it a try and going to implement it? We would appreciate your help.

**Comment by mattk42** [comment]
I have taken a stab at this and it seems to be working. Going to spend some time on unit tests and should have a pull request soon.

**Comment by palevi67** [comment]
+1

**Comment by nick7ikin** [comment]
+1

**Comment by gurbuzali** [comment]
fixed via https://github.com/hazelcast/hazelcast/pull/5658

**Comment by nick7ikin** [comment]
can I use this combination as workaround to specify lease time?
```
if (lock.tryLock(1, TimeUnit.SECONDS) {
   lock.lock(2, TimeUnit.SECONDS);
   ....
   lock.unlock();
}
```

**Comment by gurbuzali** [comment]
no need for a workaround for 3.6, we've implemented `tryLock` with lease time.
please take a look at https://github.com/hazelcast/hazelcast/blob/master/hazelcast/src/main/java/com/hazelcast/core/ILock.java#L90

for the previous versions, yes it works but you need to unlock twice since you've locked it twice:
one with `tryLock` and one with `lock`
