### ISSUE TITLE
Client-initiated query hangs on topology change

### ISSUE THREAD

**Issue by gierlachg** [hazelcast/hazelcast#18538]
A non-initiator node cancels query (i.e. due to topology change) by trying to send `QueryCancelOperation` to initiator based on [QueryId.getMemberId()](https://github.com/hazelcast/hazelcast/blob/5ef6f112e19e10346b09cfe4fb7db03a23881ce8/hazelcast/src/main/java/com/hazelcast/sql/impl/state/QueryState.java#L260) which in case of client-initiated query is the id of the client. As the result query hangs until timeout elapses.

To remediate that member-initiator id should be used.

**Comment by viliam-durina** [comment]
Wasn't this fixed by #18536?

**Comment by gierlachg** [comment]
No, this was discovered while working on #18536 - random `UUID` simulated topology change. The issue is still there.
