### ISSUE TITLE
Huge difference between Map Entries and Backup - hazelcast 3.3.3

### ISSUE THREAD

**Issue by geojins** [hazelcast/hazelcast#4786]
Problem:
I have  2 node cluster with hazelcast version 3.3.3 running. I see a huge difference between the map entries and backup. See the screenshot from mancenter.  This is leading to a memory issue. Appreciate any inputs on this behavior.
![image](https://cloud.githubusercontent.com/assets/7400217/6586148/8606c4cc-c734-11e4-9869-74e7eaa84968.png)

hazelcast.xml entry for the map:

```
<map name="DailyUsageMap">
                <map-store enabled="true">
                        <class-name>com.mycompany.core.util.cache.hazelCast.PersistenceProvider</class-name>
                        <write-delay-seconds>120</write-delay-seconds>
                </map-store>
                <indexes><index ordered="true">entryId</index></indexes>
                <backup-count>0</backup-count>
                <async-backup-count>1</async-backup-count>
                <read-backup-data>true</read-backup-data>
                <eviction-policy>NONE</eviction-policy>
        </map>
```
map-store is saving to cassandra.

Thanks,
Jins

**Comment by mesutcelik** [comment]
https://github.com/hazelcast/hazelcast/pull/4724 might have fixed the problem.

**Comment by geojins** [comment]
Thanks! However in my case both the nodes were started almost the same time  and the maps were populated after both the nodes were up. Map was populated over a period of one week with each entry having a ttl of 72 hours set.  Entries are evicted after the TTL time, but it appears as if the backups are not removed.

**Comment by ahmetmircik** [comment]
Hi @geojins, 
Can you also see that misbehavior when using __3.3.5__? It should have been fixed in that release. By the way, as you may probably know, 3.3.5 is the latest bug fixer release of 3.3.x series and all new releases in 3.3.x series are backward compatible.

**Comment by geojins** [comment]
Thanks!  I will try with 3.3.5 and post the results.

**Comment by geojins** [comment]
I have tried with 3.3.5, but still seeing the same issue.  I can see the entries being removed after the given TTL time from the entries count, but the backup count does not  reduces.
Key of this map is a string and value is a custom object. We have written our on serializer for the value object. Does this have any impact on backup ?

Screenshot of Mancenter:
![image](https://cloud.githubusercontent.com/assets/7400217/6703406/bd0205b2-ccf8-11e4-8094-5454a978b952.png)

Does using an EntryProcessor/backupEntryProcessor is advisable ? Typical size of the map is around 5-6 Million with constant read/write.

Thanks,
Jins

**Comment by ahmetmircik** [comment]
Hi @geojins, 
Thanks for testing. But unfortunately it seems the fix which i thought applied to 3.3.5 is not there it is in __3.4.1__ here https://github.com/hazelcast/hazelcast/pull/4591. 
Can you please also retry with __3.4.1__?

Thanks,

**Comment by ahmetmircik** [comment]
Hi @geojins, 
Closing this issue since it should be a solved problem with PR #4591. If the issue still appears in version __3.4.1__, please let us know that.

Thanks,
