### ISSUE TITLE
v3.4.2 Near Cache not immediately auto invalidate when updates happen in transaction.

### ISSUE THREAD

**Issue by pdca** [hazelcast/hazelcast#5018]
Enable near cache in client side (server side/cluster-member not enable near cache), below tests running in my laptop.
Client side near cache config:
```
        NearCacheConfig nearCacheConfig = new NearCacheConfig();
        nearCacheConfig.setName("nearCache_map");
        nearCacheConfig.setTimeToLiveSeconds(3600);
        nearCacheConfig.setMaxIdleSeconds(3600);
        clientConfig.addNearCacheConfig(nearCacheConfig);
```

## 1. Test update records without transaction
```
    @Test
    public void testNearCacheWithoutTxn() {
        IMap<String, Employee> imap = hzClientInst.getMap("nearCache_map");
        Employee nearCacheEmployee = imap.get("abcdefg123456"); // cache to near cache
        logger.debug("Init value: {}", nearCacheEmployee);
        logger.debug("Near-cache map stats: {}", imap.getLocalMapStats().getNearCacheStats());
        nearCacheEmployee.setActive(!nearCacheEmployee.isActive());
        imap.put(nearCacheEmployee.getName(), nearCacheEmployee);
        logger.debug("After update: {}", imap.get("abcdefg123456"));
        logger.debug("Near-cache map stats: {}", imap.getLocalMapStats().getNearCacheStats());
    }
```
output:
```
2015-04-08 00:19:04,763 2913 [main] DEBUG c.h.query.HazelcastNearCacheTest.testNearCacheWithoutTxn - Init value: com.hazelcast.query.domain.Employee@39b4cec7[name=abcdefg123456,age=60,active=false,salary=10000.0] 
2015-04-08 00:19:04,763 2913 [main] DEBUG c.h.query.HazelcastNearCacheTest.testNearCacheWithoutTxn - Near-cache map stats: NearCacheStatsImpl{ownedEntryCount=1, ownedEntryMemoryCost=200, creationTime=1428448744758, hits=0, misses=1, ratio=0.0} 
2015-04-08 00:19:04,771 2921 [main] DEBUG c.h.query.HazelcastNearCacheTest.testNearCacheWithoutTxn - After update: com.hazelcast.query.domain.Employee@2ad4cd45[name=abcdefg123456,age=60,active=true,salary=10000.0] 
2015-04-08 00:19:04,771 2921 [main] DEBUG c.h.query.HazelcastNearCacheTest.testNearCacheWithoutTxn - Near-cache map stats: NearCacheStatsImpl{ownedEntryCount=1, ownedEntryMemoryCost=200, creationTime=1428448744758, hits=0, misses=2, ratio=0.0} 
```
From the output, 2nd time IMap.get(pk) near-cache stats: "hits=0, misses=2", the near-cache is auto invalidated, this is expected, the test result is positive.

## 2. Test update records with transaction
```
    @Test
    public void testNearCacheWithTxn() throws InterruptedException {
        IMap<String, Employee> imap = hzClientInst.getMap("nearCache_map");
        imap.get("abcdefg123456"); // cache to near cache

        TransactionContext context = hzClientInst.newTransactionContext();
        context.beginTransaction();
        TransactionalMap<String, Employee> txnIMap = context.getMap("nearCache_map");
        try {
            Employee employee = txnIMap.get("abcdefg123456");
            logger.debug("Init value: {}", employee);
            // update
            employee.setActive(!employee.isActive());
            txnIMap.put(employee.getName(), employee);
            context.commitTransaction();
        } catch (Exception exp) {
            logger.error(exp.getMessage(), exp);
            context.rollbackTransaction();
        }

        //        Thread.sleep(100); // near cache should be auto expired
        Employee nearCacheEmployee = imap.get("abcdefg123456");
        logger.debug("After update: {}", nearCacheEmployee);
        logger.debug("Near-cache map stats: {}", imap.getLocalMapStats().getNearCacheStats());
    }
```

output:
```
2015-04-08 00:19:02,650 800  [main] DEBUG c.h.query.HazelcastNearCacheTest.testNearCacheWithTxn - Init value: com.hazelcast.query.domain.Employee@47b80ccb[name=abcdefg123456,age=60,active=true,salary=10000.0] 
2015-04-08 00:19:02,660 810  [main] DEBUG c.h.query.HazelcastNearCacheTest.testNearCacheWithTxn - After update: com.hazelcast.query.domain.Employee@1d0ac035[name=abcdefg123456,age=60,active=true,salary=10000.0] 
2015-04-08 00:19:02,663 813  [main] DEBUG c.h.query.HazelcastNearCacheTest.testNearCacheWithTxn - Near-cache map stats: NearCacheStatsImpl{ownedEntryCount=1, ownedEntryMemoryCost=200, creationTime=1428448742602, hits=1, misses=1, ratio=1.0} 
```
From output, the Employee Object active is still := true, and from near-cache stats: "hits=1, misses=1", the Employee Object is hits=1 it should be get from near-cache, this is stale (wrong) data, this is not expected result.
If uncomment "Thread.sleep(100);" will get correct (not stale) data.

**So the question is you should invalidate the near-cache when txnIMap.put(..) happens, similar function/behavior like IMap.put(..).**

**Comment by bwzhang2011** [comment]
@pdca, any update with the issue ? is it confirmed or not ?

**Comment by pdca** [comment]
@bwzhang2011 what king of update you want?

**Comment by bwzhang2011** [comment]
@pdca, sorry for not response. my last comment just want to ask whether it's resolved in latest branch ore still an open issue ?

**Comment by pdca** [comment]
@bwzhang2011 test again with v3.5.3, the bug still not fixed. I didnot work with hazelcast for a long time, you should ownership to make sure this test scenario covered for the future release version.

**Comment by ahmetmircik** [comment]
Tried with latest 3.6.3, it seems ok. Please also try it yourself and comment here if you still experience the issue. Now i'm closing this issue.
