### ISSUE TITLE
[TEST-FAILURE] client SumAggregationTest timeout

### ISSUE THREAD

**Issue by bilalyasar** [hazelcast/hazelcast#5096]
```
02:36:39 Running com.hazelcast.client.mapreduce.aggregation.SumAggregationTest
03:47:15 Build timed out (after 100 minutes). Marking the build as aborted.
```
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-OpenJDK6/507/console

**Comment by bilalyasar** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-OpenJDK6/507/console

**Comment by bilalyasar** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x/3034/console

**Comment by sancar** [comment]
Closing this one since it did not failed over 1 month.

**Comment by mesutcelik** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-OpenJDK7-Quality-Outreach/65/

**Comment by bilalyasar** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-sonar/637/console

**Comment by sancar** [comment]
f79e8d31a69b9fa3d7257234c5d8176585cc1876
@jerrinot Why did we re-enabled Aggregation tests? Did someone work on Map-Reduce to fix those ?
Tests are still failing with timeout.

**Comment by jerrinot** [comment]
@sancar: I'm sorry, I missed the mention. 
I fixed a race condition in M/R #6082 quite some time ago.

**Comment by sancar** [comment]
But tests are still failing. Do you think should we re-ignore the tests in include in our "Fixing MapReduce problems" prd ?

**Comment by jerrinot** [comment]
I'm afraid that's our best option right now. Let me send a PR.

**Comment by jerrinot** [comment]
@sancar: #6823

**Comment by sancar** [comment]
Thanks @jerrinot . Closing this one and merging to https://github.com/hazelcast/hazelcast/issues/5916
