### ISSUE TITLE
IMap.destroy() - map is destroyed and then immediately recreated

### ISSUE THREAD

**Issue by bzlat** [hazelcast/hazelcast#5554]
Creating this issue as suggested by @bilalyasar (see [discussion on the Hazelcast Google Groups forum] (https://groups.google.com/forum/#!topic/hazelcast/G1P43tORJPA))

Hazelcast version that you use: ```3.4.2```, ```3.5```
Cluster size: ```1```
Number of the clients: ```1```
Version of Java: ```OracleJDK 1.7.0_80, x86_64```, ```OracleJDK 1.8.0_45, x86_64```
Operating system: ```OS X Yosemite 10.10.3 (14D136)```
Logs and stack traces: See the console output from executing the TestNG test case below
Detailed description of the steps to reproduce your issue: See the TestNG test case below
Unit test with the hazelcast.xml file: 

```java
import static org.testng.Assert.assertEquals;
import static org.testng.Assert.assertNotNull;

import org.testng.annotations.AfterClass;
import org.testng.annotations.BeforeClass;
import org.testng.annotations.Test;

import com.hazelcast.client.HazelcastClient;
import com.hazelcast.core.DistributedObjectEvent;
import com.hazelcast.core.DistributedObjectListener;
import com.hazelcast.core.Hazelcast;
import com.hazelcast.core.HazelcastInstance;
import com.hazelcast.core.IMap;

public class IMapDestroyTest {

	private HazelcastInstance server;
	private HazelcastInstance client;

	@BeforeClass
	public void setUpBeforeClass() {
		server = Hazelcast.newHazelcastInstance();
		sleep(2000);
		client = HazelcastClient.newHazelcastClient();
		client.addDistributedObjectListener(new DistributedObjectListener() {
			@Override public void distributedObjectDestroyed(final DistributedObjectEvent event) {
				System.out.println("\n\tdistributedObjectDestroyed(): " + event);
			}
			@Override public void distributedObjectCreated(final DistributedObjectEvent event) {
				System.out.println("\n\tdistributedObjectCreated(): " + event);
			}
		});
	}

	@AfterClass
	public void tearDownAfterClass() {
		client.shutdown();
		server.shutdown();
	}

	@Test
	public void testIMapDestroy() {
		System.out.print("Creating 'foo' map... ");
		IMap<String, String> fooMap = client.getMap("foo");
		assertNotNull(fooMap);
		System.out.println("done.");
		System.out.println("All known distributed objects: " + client.getDistributedObjects());
		System.out.print("Inserting an entry... ");
		fooMap.put("fu", "bar");
		System.out.print("done.\nRetrieving the entry... ");
		String value = fooMap.get("fu");
		assertEquals(value, "bar");
		System.out.print("done.\nDestroying the map... ");
		fooMap.destroy();
		System.out.println("done.");
		System.out.println("All known distributed objects: " + client.getDistributedObjects());
	}

	private void sleep(final int millis) {
		try {
			Thread.sleep(millis);
		} catch (InterruptedException e) {
			Thread.currentThread().interrupt();
		}
	}
}
```

Console output:
```
Creating 'foo' map...
        distributedObjectCreated(): DistributedObjectEvent{eventType=CREATED, serviceName='hz:impl:mapService', distributedObject=IMap{name='foo'}}
done.
All known distributed objects: [IMap{name='foo'}]
Inserting an entry... done.
Retrieving the entry... done.
Destroying the map...
        distributedObjectDestroyed(): DistributedObjectEvent{eventType=DESTROYED, serviceName='hz:impl:mapService', distributedObject=IMap{name='foo'}}
        distributedObjectCreated(): DistributedObjectEvent{eventType=CREATED, serviceName='hz:impl:mapService', distributedObject=IMap{name='foo'}}
done.
All known distributed objects: [IMap{name='foo'}]
```

**Comment by gurbuzali** [comment]
related/duplicate https://github.com/hazelcast/hazelcast/issues/5592

**Comment by gurbuzali** [comment]
should be fixed via https://github.com/hazelcast/hazelcast/pull/5594

**Comment by bzlat** [comment]
I've just tested with the lastest Hazelcast version ```3.5.1``` and this test still fails. My test is now slightly different from the one I originally posted (it now uses lifecycle event listener to detect server and client start-up, instead of sleeping), but I tested with both and both fail. Here's the code of my latest test:

```java
import static org.testng.Assert.assertEquals;
import static org.testng.Assert.assertNotNull;
import static org.testng.Assert.assertTrue;

import java.util.concurrent.CountDownLatch;
import java.util.concurrent.TimeUnit;

import org.testng.annotations.AfterClass;
import org.testng.annotations.BeforeClass;
import org.testng.annotations.Test;

import com.hazelcast.client.HazelcastClient;
import com.hazelcast.client.config.ClientConfig;
import com.hazelcast.client.config.XmlClientConfigBuilder;
import com.hazelcast.config.Config;
import com.hazelcast.config.ListenerConfig;
import com.hazelcast.config.XmlConfigBuilder;
import com.hazelcast.core.DistributedObjectEvent;
import com.hazelcast.core.DistributedObjectListener;
import com.hazelcast.core.Hazelcast;
import com.hazelcast.core.HazelcastInstance;
import com.hazelcast.core.IMap;
import com.hazelcast.core.LifecycleEvent;
import com.hazelcast.core.LifecycleEvent.LifecycleState;
import com.hazelcast.core.LifecycleListener;

public class IMapDestroyTest {

	private HazelcastInstance server;
	private HazelcastInstance client;

	@BeforeClass
	public void setUpBeforeClass() throws InterruptedException {
		final CountDownLatch signalStarted = new CountDownLatch(2);

		server = startServer(signalStarted);
		client = startClient(signalStarted);

		signalStarted.await(15, TimeUnit.SECONDS);
	}

	private HazelcastInstance startServer(final CountDownLatch signalStarted) {
		return Hazelcast.newHazelcastInstance(serverConfig(signalStarted));
	}

	private Config serverConfig(final CountDownLatch signalStarted) {
		Config config = new XmlConfigBuilder().build();
		config.addListenerConfig(new ListenerConfig(new StartedListener(signalStarted)));
		return config;
	}

	private HazelcastInstance startClient(final CountDownLatch signalStarted) {
		HazelcastInstance client = HazelcastClient.newHazelcastClient(clientConfig(signalStarted));

		client.addDistributedObjectListener(new DistributedObjectListener() {
			@Override public void distributedObjectDestroyed(final DistributedObjectEvent event) {
				System.out.println("distributedObjectDestroyed(): " + event);
			}
			@Override public void distributedObjectCreated(final DistributedObjectEvent event) {
				System.out.println("distributedObjectCreated(): " + event);
			}
		});

		return client;
	}

	private ClientConfig clientConfig(final CountDownLatch signalStarted) {
		ClientConfig clientConfig = new XmlClientConfigBuilder().build();
		clientConfig.addListenerConfig(new ListenerConfig(new StartedListener(signalStarted)));
		return clientConfig;
	}

	@AfterClass
	public void tearDownAfterClass() {
		client.shutdown();
		server.shutdown();
	}

	@Test
	public void testIMapDestroy() {
		assertTrue(client.getDistributedObjects().isEmpty(), "There should be no distributed objects on a fresh start");

		IMap<String, String> fooMap = client.getMap("foo");

		assertNotNull(fooMap);
		assertEquals(client.getDistributedObjects().size(), 1, "There should be one distributed object - the 'foo' IMap");

		fooMap.put("fu", "bar");
		String value = fooMap.get("fu");

		assertEquals(value, "bar");

		fooMap.destroy();

		assertTrue(client.getDistributedObjects().isEmpty(), "There should be no distributed objects after destroying the map");
	}

	private static class StartedListener implements LifecycleListener {
		private final CountDownLatch signalStarted;

		public StartedListener(final CountDownLatch signalStarted) {
			this.signalStarted = signalStarted;
		}

		@Override
		public void stateChanged(final LifecycleEvent event) {
			if (event.getState() == LifecycleState.STARTED) {
				signalStarted.countDown();
			}
		}
	}
}
```

And this is the test output:

```
distributedObjectCreated(): DistributedObjectEvent{eventType=CREATED, serviceName='hz:impl:mapService', distributedObject=IMap{name='foo'}}
distributedObjectDestroyed(): DistributedObjectEvent{eventType=DESTROYED, serviceName='hz:impl:mapService', distributedObject=IMap{name='foo'}}
distributedObjectCreated(): DistributedObjectEvent{eventType=CREATED, serviceName='hz:impl:mapService', distributedObject=IMap{name='foo'}}
FAILED: testIMapDestroy
java.lang.AssertionError: There should be no distributed objects after destroying the map expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at my.experiments.hazelcast.IMapDestroyTest.testIMapDestroy(IMapDestroyTest.java:91)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:659)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:845)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1153)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
```

Does this work for you?

**Comment by gurbuzali** [comment]
Thank you @bzlat for the provided test, I'll try to look at it asap

**Comment by jerrinot** [comment]
The test is great, many thanks @bzlat for your effort here.

I see what is going on: The test has a `DistributedObjectListener` registered. 

When it calls `map.destroy()` then the map is indeed destroyed, however the destruction generates an event which is received by a client and the client calls the [listener](https://github.com/jerrinot/hazelcast/blob/bff44c10245d300c86d8a2e596bd6fd00868da86/hazelcast-client/src/main/java/com/hazelcast/client/spi/ProxyManager.java#L340) which happens to [re-create(!)](https://github.com/jerrinot/hazelcast/blob/bff44c10245d300c86d8a2e596bd6fd00868da86/hazelcast-client/src/main/java/com/hazelcast/client/spi/ProxyManager.java#L346) the proxy again.

It's indeed a bug and we should change the logic here.
