### ISSUE TITLE
VersionCheckTest.testVersionCheckParameters

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast#7192]
```
java.lang.AssertionError: Values should be different. Actual: 0
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failEquals(Assert.java:185)
	at org.junit.Assert.assertNotEquals(Assert.java:161)
	at org.junit.Assert.assertNotEquals(Assert.java:175)
	at com.hazelcast.util.VersionCheckTest.testVersionCheckParameters(VersionCheckTest.java:58)
```

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.maintenance-IbmJDK1.8/com.hazelcast$hazelcast/23/testReport/junit/com.hazelcast.util/VersionCheckTest/testVersionCheckParameters/

**Comment by kobalski** [comment]
Should be fixed via https://github.com/hazelcast/hazelcast/commit/418784b5a04434806caa87ee9e61b2b6cb2b5905
@jerrinot I applied a fix with direct commit. The test fails because cluster uptime is `0`.  I added ` assertClusterSizeEventually(1, hz1);` assignment to the test.

**Comment by jerrinot** [comment]
@kobalski: I can still reproduce the issue even with your change.  Just annotate it with `@Repeat(1000)` and watch. (you have to have a reasonably fast machine and perhaps a real OS?:)) 

The test assumes the cluster-time is always greater than 0 (ms). The cluster time is defined as "no. of ms since cluster has started". However if the test is too fast then the cluster time is 0 -> the test is failing. Introducing the `assertClusterSizeEventually(1, hz1);` changes nothing here.

**Comment by jerrinot** [comment]
adding [`sleepAtLeastMillis(1);`](https://github.com/jerrinot/hazelcast/blob/6299958ca9504132722d12bc0ecab352bc14c4ca/hazelcast/src/test/java/com/hazelcast/util/VersionCheckTest.java#L45) would fix the test. I think it could be a final solution. 

However let me think a bit about the semantic of the cluster uptime. I am not sure if uptime "0" makes any sense at all. There are at least 2 possible definitions of "uptime". 

Our current definition is "it's at least n ms since the cluster went up". The other possible semantic of uptime is "it's n-th ms of the cluster being alive".

**Comment by jerrinot** [comment]
right, so according [to](https://github.com/jerrinot/hazelcast/blob/125404ca44f7b1d02323d7f4e9df824887394bd4/hazelcast/src/main/java/com/hazelcast/cluster/ClusterClock.java#L38) `Up-time of cluster is calculated as ClusterClock#getClusterTime - clusterStartTime`. 

In this case uptime 0 makes sense.

**Comment by kobalski** [comment]
Yes and `clusterStartTime` is set when first node becomes the master node. Master node sends this value to joining nodes.  I use `Clock.currentTimeMillis()`, maybe on faster machines and real os, `ms` resolution of jvm causes the value `0` for uptime.
